server:
  port: 8082

spring:
  application:
    name: springcloud-dept-feign

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
feign:
  hystrix:
    enabled: true
