spring:
  application:
    name: config-client
  rabbitmq:
    addresses: ruipeng.site
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true


server:
  port: 8881

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
